apiVersion: v1
kind: Secret
type: ibm/ibmc-s3fs
metadata:
  name: test-secret
data:
  access-key: <access key encoded in base64>
  secret-key: <secret key encoded in base64>
  res-conf-apikey: <api key (with Manager role for setting firewall rules) encoded in base64>
stringData:
  allowed_ips: "1.1.1.1, 171.76.190.0/16"
